/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciofinal;

import javax.swing.ImageIcon;

/**
 *
 * @author Walkiria
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/ejerciciofinal/home.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArchivos = new javax.swing.JMenu();
        MenuVentas = new javax.swing.JMenuItem();
        MenuAgentes = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenuItem();
        MenuHerramientas = new javax.swing.JMenu();
        MenuConversor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuArchivos.setText("Archivos ");

        MenuVentas.setText("Ventas");
        MenuArchivos.add(MenuVentas);

        MenuAgentes.setText("Agentes");
        MenuAgentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAgentesActionPerformed(evt);
            }
        });
        MenuArchivos.add(MenuAgentes);

        MenuSalir.setText("Salir");
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });
        MenuArchivos.add(MenuSalir);

        jMenuBar1.add(MenuArchivos);

        MenuHerramientas.setText("Herramientas");

        MenuConversor.setText("Conversor Dolar");
        MenuConversor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConversorActionPerformed(evt);
            }
        });
        MenuHerramientas.add(MenuConversor);

        jMenuBar1.add(MenuHerramientas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_MenuSalirActionPerformed

    private void MenuConversorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConversorActionPerformed
        PantallaConversor conversor;
        conversor = new PantallaConversor();
        conversor.setVisible(true);
        
    }//GEN-LAST:event_MenuConversorActionPerformed

    private void MenuAgentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAgentesActionPerformed
        ListadoAgentes listado;
        listado = new ListadoAgentes();
        listado.setVisible(true);
    }//GEN-LAST:event_MenuAgentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAgentes;
    private javax.swing.JMenu MenuArchivos;
    private javax.swing.JMenuItem MenuConversor;
    private javax.swing.JMenu MenuHerramientas;
    private javax.swing.JMenuItem MenuSalir;
    private javax.swing.JMenuItem MenuVentas;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
